use_frameworks!

platform :ios, '9.0'

target 'LSJHBannerView_Example' do
  pod 'LSJHBannerView', :path => '../'

  target 'LSJHBannerView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
